- name: Manage nmap installation based on NetBox nmap tag
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Install nmap if nmap tag is present
      ansible.builtin.apt:
        name: nmap
        state: present
      when: "'nmap' in (netbox_device.device.tags | map(attribute='name') | list)"

    - name: Remove nmap if nmap tag is absent
      ansible.builtin.apt:
        name: nmap
        state: absent
        purge: yes
      when: "'nmap' not in (netbox_device.device.tags | map(attribute='name') | list)"
