- name: Manage nmap installation based on NetBox nmap tag
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Install nmap if nmap tag is present
      ansible.builtin.apt:
        name: nmap
        state: present
      when: "'nmap' in hostvars[inventory_hostname].tags"

    - name: Remove nmap if nmap tag is absent
      ansible.builtin.apt:
        name: nmap
        state: absent
        purge: yes
      when: "'nmap' not in hostvars[inventory_hostname].tags"

    - name: Set NetBox status to Offline if nmap tag is absent
      netbox.netbox.netbox_device:
        netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          name: "{{ inventory_hostname }}"
          status: Offline
        state: present
      when: "'nmap' not in hostvars[inventory_hostname].tags"
