- name: Print tags for pgsql-citus-2
  hosts: pgsql-citus-2
  gather_facts: false  # Evita coletar facts do sistema
  tasks:
    - name: Display NetBox tags for pgsql-citus-2
      ansible.builtin.debug:
        msg: "Tags: {{ hostvars[inventory_hostname].tags }}"
