---
- name: Print facts for pgsql-citus-2
  hosts: pgsql-citus-2
  gather_facts: true  # Habilita a coleta de facts
  tasks:
    - name: Display all facts for pgsql-citus-2
      ansible.builtin.debug:
        var: ansible_facts
